export const APP_ROUTES = {
  HOME:         '',
  CATEGORY:     'category',
  PRODUCT:      'product',
  SHOP:         'shop',
  NEW_ARRIVALS: 'new-arrivals',
  TRENDING:     'trending',
  ADMIN:        'admin',
  NOT_FOUND:    'not-found',
  MARKETING:    'marketing/dashboard',
  CONTENT_CALENDAR: 'marketing/calendar',
  PROMPT_STUDIO: 'marketing/prompt-studio',
  FASHION_KNOWLEDGE: 'marketing/fashion-knowledge',
  BRAND_VOICE_TRAINER: 'marketing/brand-voice',
  CONTENT_QUALITY: 'marketing/content-quality',
  IMAGE_VARIATIONS: 'marketing/image-variations',
  PROMPT_TEMPLATE_ENGINE: 'marketing/prompt-templates',
  AI_WORKFLOW_BUILDER: 'marketing/workflow',
  GENERATION_QUEUE: 'marketing/queue',
  AI_COST_DASHBOARD: 'marketing/cost',
  BRAND_ASSET_LIBRARY: 'marketing/assets',
  AI_REVIEW_PANEL: 'marketing/review',
  AI_BRAIN_CONFIG: 'marketing/brain',
  AI_MEMORY: 'marketing/memory',
  PROMPT_ORCHESTRATOR: 'marketing/orchestrator',
  AI_AGENTS: 'marketing/agents',
  CAMPAIGN_PIPELINE: 'marketing/pipeline',
  IMAGE_DIRECTOR: 'marketing/image-director',
  AI_REVIEWER: 'marketing/reviewer',
  MULTI_STEP_GENERATION: 'marketing/generation',
  AI_PROVIDER: 'marketing/providers',
  AI_ORCHESTRATOR: 'marketing/ai-orchestrator',
  PIPELINE_DESIGNER: 'marketing/pipeline-designer',
  CAMPAIGN_GENERATOR: 'marketing/campaign-generator',
  AI_DECISION_ENGINE: 'marketing/decision-engine',
  FASHION_INTELLIGENCE: 'marketing/fashion-intelligence',
  MARKETING_STRATEGIST: 'marketing/strategist',
  RECOMMENDATION_CENTER: 'marketing/recommendations',
  AI_CEO_DASHBOARD: 'marketing/ceo-dashboard',
  AI_TREND_ANALYSIS: 'marketing/trend-analysis',
  AI_CONTENT_PLANNER: 'marketing/content-planner',
} as const;

export type AppRoute = (typeof APP_ROUTES)[keyof typeof APP_ROUTES];

/* Category IDs — single source of truth */
export const CATEGORY_IDS = {
  LONG_KURTAS:   'long-kurtas',
  SHORT_KURTAS:  'short-kurtas',
  TWO_PIECE:     '2-piece-sets',
  THREE_PIECE:   '3-piece-sets',
} as const;
