using System.Text.Json.Serialization;
using Vrindaya.Api.AI.Campaigns.Models;

namespace Vrindaya.Api.AI.Campaigns.Dtos;

/// <summary>
/// A single generated campaign suggestion, with its computed score and
/// priority ordering signal. Score is always populated; higher is better.
/// </summary>
public class CampaignSuggestionDto
{
    public string ProductId { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string Category { get; set; } = string.Empty;

    public string Title { get; set; } = string.Empty;

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public CampaignObjective Objective { get; set; }

    public string Rationale { get; set; } = string.Empty;

    /// <summary>0..100 deterministic score used to order suggestions (descending).</summary>
    public int Score { get; set; }

    [JsonConverter(typeof(JsonStringEnumConverter))]
    public CampaignPriority Priority { get; set; }

    public double Confidence { get; set; }

    public double ExpectedRoi { get; set; }

    public long EstimatedRevenue { get; set; }

    /// <summary>Rich marketing copy generated by the AI provider (captions, scripts, hashtags, CTA).</summary>
    public string InstagramCaption { get; set; } = string.Empty;

    /// <summary>Short-form video (Reel/Short) script for this campaign.</summary>
    public string ReelScript { get; set; } = string.Empty;

    /// <summary>Ordered carousel slide copy for this campaign.</summary>
    public List<string> CarouselSlides { get; set; } = new();

    /// <summary>Social hashtags for this campaign.</summary>
    public List<string> Hashtags { get; set; } = new();

    /// <summary>Call-to-action copy for this campaign.</summary>
    public string Cta { get; set; } = string.Empty;
}