using Vrindaya.Api.AI.Flipkart.Models;

namespace Vrindaya.Api.AI.Flipkart.DTOs;

/// <summary>
/// Product-intelligence analysis result. Every metric is derived
/// deterministically from the product's own data — no Firestore reads, no
/// randomness. The single exception is <see cref="Analysis"/>, which is written
/// by the configured AI provider from those metrics and is blank when no
/// narration was produced.
/// </summary>
public sealed class ProductIntelligenceResultDto
{
    /// <summary>Unique product identifier.</summary>
    public string ProductId { get; set; } = string.Empty;

    /// <summary>Human-readable product name.</summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>Product category.</summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>Absolute profit per unit (SellingPrice - PurchaseCost).</summary>
    public double ProfitMargin { get; set; }

    /// <summary>Gross margin ratio as a percentage (0–100).</summary>
    public double MarginPercentage { get; set; }

    /// <summary>Categorisation of the current stock level.</summary>
    public StockHealth StockHealth { get; set; }

    /// <summary>Units sold per day since the product was created.</summary>
    public double SalesVelocity { get; set; }

    /// <summary>Days of inventory remaining at the current velocity (null when velocity is zero).</summary>
    public double? DaysOfInventory { get; set; }

    /// <summary>Composite inventory-risk severity.</summary>
    public InventoryRisk InventoryRisk { get; set; }

    /// <summary>Deterministic, single best business action for this product.</summary>
    public RecommendedAction RecommendedAction { get; set; }

    /// <summary>Overall product score (0–100) — weighted composite of margin quality, stock health, sales velocity, sales volume, product age and risk mitigation.</summary>
    public int OverallProductScore { get; set; }

    /// <summary>
    /// Written analysis of the metrics above (positioning, audience fit,
    /// pricing, stock guidance, next steps), generated by the configured AI
    /// provider. Empty when narration was unavailable — every metric above
    /// remains valid regardless.
    /// </summary>
    public string Analysis { get; set; } = string.Empty;
}
